import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import assert from 'assert'

const __dirname = dirname(fileURLToPath(import.meta.url))
const app = readFileSync(resolve(__dirname, '../src/App.vue'), 'utf8')
const router = readFileSync(resolve(__dirname, '../src/router/index.ts'), 'utf8')
const apiPath = resolve(__dirname, '../src/api/caseFund.ts')
const viewPath = resolve(__dirname, '../src/views/case-fund/PaymentRegisterView.vue')
const refundViewPath = resolve(__dirname, '../src/views/case-fund/RefundRegisterView.vue')

assert(app.includes('menu:case_fund:payment'), 'sidebar should check payment register menu permission')
assert(app.includes('index="/case-fund/payments"'), 'sidebar should route to case fund payment register')
assert(app.includes('案款业务'), 'sidebar should show case fund business menu')
assert(app.includes('案款缴费登记'), 'sidebar should show payment register menu item')
assert(app.includes('案款退付登记'), 'sidebar should reserve refund register menu item')
assert(!app.includes('index="/case-fund/refunds" disabled'), 'refund register menu item should be enabled')

assert(router.includes("const PaymentRegisterView = () => import('../views/case-fund/PaymentRegisterView.vue')"), 'router should lazy-load payment register view')
assert(router.includes("'/case-fund/payments'"), 'router should register payment page route')
assert(router.includes("permission: 'menu:case_fund:payment'"), 'payment route should require payment menu permission')
assert(router.includes("const RefundRegisterView = () => import('../views/case-fund/RefundRegisterView.vue')"), 'router should lazy-load refund register view')
assert(router.includes("'/case-fund/refunds'"), 'router should register refund page route')
assert(router.includes("permission: 'menu:case_fund:refund'"), 'refund route should require refund menu permission')

assert(existsSync(apiPath), 'case fund API wrapper should exist')
assert(existsSync(viewPath), 'payment register view should exist')
assert(existsSync(refundViewPath), 'refund register view should exist')

const api = readFileSync(apiPath, 'utf8')
const view = readFileSync(viewPath, 'utf8')
const refundView = existsSync(refundViewPath) ? readFileSync(refundViewPath, 'utf8') : ''
assert(api.includes("apiAction('/caseFund/paymentList'"), 'case fund API should expose payment list')
assert(api.includes("apiAction('/caseFund/paymentImport'"), 'case fund API should expose payment import')
assert(api.includes('updated: number'), 'payment import API should expose updated row count')
assert(api.includes("apiAction('/caseFund/refundList'"), 'case fund API should expose refund list')
assert(api.includes("apiAction('/caseFund/refundImport'"), 'case fund API should expose refund import')
assert(api.includes("apiAction('/caseFund/refundGenerateVoucher'"), 'case fund API should expose refund voucher generation')
assert(view.includes('choosePaymentImportFile'), 'payment view should provide import file picker')
assert(view.includes('handlePaymentImportFile'), 'payment view should handle selected xls file')
assert(view.includes('caseFundApi.importPayments'), 'payment view should call payment import API')
assert(view.includes('覆盖${result.updated || 0}条'), 'payment view should show overwritten import row count')
assert(view.includes('caseFundApi.paymentList'), 'payment view should load payment list API')
assert(view.includes('voucher_status'), 'payment view should show voucher generation status')
assert(view.includes('date_start'), 'payment view should query by payment start date')
assert(view.includes('date_end'), 'payment view should query by payment end date')
assert(!view.includes('v-model="filters.period"'), 'payment view should not use accounting period as the first date filter')
assert(view.includes('今天') && view.includes('本周') && view.includes('本月') && view.includes('本年'), 'payment view should provide quick payment date ranges')
assert(view.includes('@click="query"'), 'payment view should include a query button')
assert(!view.includes('>刷新</el-button>'), 'payment view should not keep a separate refresh button')
assert(refundView.includes('chooseRefundImportFile'), 'refund view should provide import file picker')
assert(refundView.includes('handleRefundImportFile'), 'refund view should handle selected xls file')
assert(refundView.includes('caseFundApi.importRefunds'), 'refund view should call refund import API')
assert(refundView.includes('caseFundApi.refundList'), 'refund view should load refund list API')
assert(refundView.includes('caseFundApi.refundGenerateVoucher'), 'refund view should generate vouchers')
assert(refundView.includes('handleGenerateVoucher'), 'refund view should handle voucher generation')
assert(refundView.includes('selectedRefundIds'), 'refund view should keep selected refund ids')
assert(refundView.includes('type="selection"'), 'refund view should allow selecting refund rows')
assert(refundView.includes('voucher_status'), 'refund view should show voucher generation status')
assert(refundView.includes('date_start'), 'refund view should query by refund start date')
assert(refundView.includes('date_end'), 'refund view should query by refund end date')
assert(refundView.includes('今天') && refundView.includes('本周') && refundView.includes('本月') && refundView.includes('本年'), 'refund view should provide quick refund date ranges')
assert(refundView.includes('@click="query"'), 'refund view should include a query button')

console.log('Case fund menu test passed')
